import Foundation

/// Enables synthesized descriptions for an enum, struct, class, or actor.
///
/// `@Describable` only switches synthesis on; the text comes from
/// ``Description(_:)`` attributes on the type and, for enums, on its cases:
///
/// ```swift
/// @Describable
/// @Description("User(id: {id}, name: {name})")
/// struct User {
///     let id: Int
///     let name: String
/// }
/// ```
///
/// By default the macro generates `CustomStringConvertible`, and additionally
/// `LocalizedError` when the declaration lists `Error` in its inheritance
/// clause. Every target that has a `@Description` is generated too, such as
/// `.debug` or a custom property.
///
/// - Parameter generating: The targets to generate instead of the defaults,
///   e.g. `[.debug]` for a type that should only be
///   `CustomDebugStringConvertible`.
@attached(
    extension,
    conformances: CustomStringConvertible, CustomDebugStringConvertible, LocalizedError,
    names: named(description), named(debugDescription), named(errorDescription), arbitrary
)
@attached(peer)
public macro Describable(
    generating: Set<DescriptionTarget> = []
) = #externalMacro(module: "DescriptionMacros", type: "DescribableMacro")

/// The main text of a type or enum case: `description`, and the fallback for
/// every other target without its own text.
///
/// Placeholders refer to properties declared in the type's body, or to an enum
/// case's associated values by label (`{code}`) or position (`{0}`). They may
/// use member paths (`{info.id}`), optional chaining (`{user?.name}`), a
/// literal default (`{user?.name ?? "anonymous"}`), and presence checks
/// (`{user?}`, rendering `true` or `false`). Use `{{` and `}}` for literal
/// braces.
@attached(peer)
public macro Description(
    _ template: String
) = #externalMacro(module: "DescriptionMacros", type: "DescriptionMacro")

/// The text of one target, such as `.error`, `.debug`, or a custom property:
///
/// ```swift
/// @Describable
/// enum LoadError: Error {
///     @Description("loadFailed({0})")
///     @Description(.error, "Could not load {0}.")
///     @Description("analyticsName", "load_failed")
///     case loadFailed(URL)
/// }
/// ```
@attached(peer)
public macro Description(
    _ target: DescriptionTarget,
    _ template: String
) = #externalMacro(module: "DescriptionMacros", type: "DescriptionMacro")

/// A `String` property that `@Describable` generates.
///
/// Use a string literal, or ``property(_:)``, to generate a property of your
/// own, for example one required by your own protocol. Declare that protocol
/// on the type yourself; the macro supplies the property.
public struct DescriptionTarget: Hashable, Sendable, ExpressibleByStringLiteral {
    /// The property's name.
    public let name: String

    /// `description`, from `CustomStringConvertible`.
    public static let description = DescriptionTarget(name: "description")
    /// `errorDescription`, from `LocalizedError`.
    public static let error = DescriptionTarget(name: "errorDescription")
    /// `debugDescription`, from `CustomDebugStringConvertible`.
    public static let debug = DescriptionTarget(name: "debugDescription")

    /// A property of your own named `name`.
    public static func property(_ name: String) -> DescriptionTarget {
        DescriptionTarget(name: name)
    }

    public init(stringLiteral name: String) {
        self.init(name: name)
    }

    private init(name: String) {
        self.name = name
    }
}

/// `LocalizedError`, re-exposed so that code generated by `@Describable` can
/// name the protocol in files that do not import Foundation themselves.
///
/// This is an implementation detail of the macro; use `LocalizedError`
/// directly in your own code.
public typealias _DescribableLocalizedError = LocalizedError
