import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

/// `@Describable`: enables synthesis of `description`, `errorDescription`,
/// and `debugDescription` for enums, structs, classes, and actors. The text
/// comes from `@Description` attributes. Custom properties are generated by
/// `@DescribableProperties`, but validated here.
public enum DescribableMacro: ExtensionMacro, PeerMacro {
    /// Generated code is laid out by the macro itself. Automatic formatting
    /// would also reformat expressions copied from raw templates, e.g.
    /// turning `{ $0 }.count` into `{ $0 } .count`.
    public static var formatMode: FormatMode { .disabled }

    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [ExtensionDeclSyntax] {
        var log = DiagnosticLog()
        let request = DescriptionPipeline.request(describable: node, declaration: declaration, in: context, log: &log)
        let generated = request.map { DescriptionPipeline.generate(for: $0, log: &log) }
        if let request, let generated {
            ConformanceValidation.validate(request, targets: generated.targets, protocols: protocols, log: &log)
            requirePropertiesMacro(for: generated.targets, in: request, log: &log)
        }
        log.emit(in: context)
        guard let generated, !log.hasErrors else {
            return []
        }
        let builtIns = generated.targets.filter { !$0.isCustomProperty }
        guard !builtIns.isEmpty else {
            return []
        }
        return DescriptionPipeline.extensionDecl(
            for: type,
            conformances: builtIns.compactMap(\.conformance),
            members: generated.members { !$0.isCustomProperty }
        )
    }

    /// Everything but the extension is a type-level concern, so the macro
    /// only generates code through its extension role. The peer role exists
    /// so that attaching `@Describable` to something that is not a type
    /// produces a diagnostic from the macro rather than a generic compiler
    /// error about macro roles.
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        if !declaration.isProtocol(DeclGroupSyntax.self) {
            context.diagnose(Diagnostic(node: node, message: DescriptionDiagnostic.unsupportedDeclaration))
        }
        return []
    }

    /// Custom properties need `@DescribableProperties`, which declares the
    /// arbitrary member names they require.
    private static func requirePropertiesMacro(
        for targets: [DescriptionTarget],
        in request: ExpansionRequest,
        log: inout DiagnosticLog
    ) {
        let custom = targets.filter(\.isCustomProperty)
        guard !custom.isEmpty,
              request.typeAttributes.attribute(named: AttributeArguments.propertiesAttribute) == nil else {
            return
        }
        log.report(
            .customTargetsRequireProperties(names: custom.map(\.propertyName)),
            at: request.attribute,
            fixIts: FixIts.addAttribute("@DescribableProperties", afterDescribableIn: request.typeAttributes)
                .map { [$0] } ?? []
        )
    }
}
